### ISSUE TITLE
Certificate issue while downloading index data

### ISSUE THREAD

**Issue by tjagad** [sahilgupta/hakija#5]
It seems there is some problem to download the index data due to certificate error. Kindly check the log below.

Log Message: Checking for data existence...
Log Message: Downloading bhavcopy...
Log Message: Bhavcopy succesfully fetched!
Log Message: Downloading NSE500 index data...
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Log Message: Error in downloading NSE500 index data. Kindly retry later.
Log Message: Downloading NSE100 index data...
Log Message: Error in downloading NSE100 index data. Kindly retry later.
Log Message: Downloading NIFTYJUNIOR index data...
Log Message: Downloading NSEMIDCAP index data...
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Log Message: Error in downloading NSEMIDCAP index data. Kindly retry later.
Log Message: Downloading NSEIT index data...
Log Message: Downloading BANKNIFTY index data...
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Log Message: Error in downloading BANKNIFTY index data. Kindly retry later.
Log Message: Downloading VIX index data...
Log Message: Error in downloading VIX index data. Kindly retry later.
Log Message: Downloading NSENIFTY index data...
Log Message: Downloading MIDCAP50 index data...
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Log Message: Error in downloading MIDCAP50 index data. Kindly retry later.
Log Message: File successfully written.

**Comment by sahilgupta** [comment]
@tjagad The SSL certificate problem has already been fixed in 13643088e364
